### ISSUE TITLE
warning @ulixee/cloud > @ulixee/datastore-core > vm2@3.9.19: The library contains critical security issues

### ISSUE THREAD

**Issue by dzxt** [ulixee/platform#190]
Hi, i faced with yarn warning
@ulixee/cloud > @ulixee/datastore-core > vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm

**Comment by blakebyrnes** [comment]
Thanks. This should not impact your security unless you are using Datastores directly. We will fix the warning in the next version.
