### ISSUE TITLE
@ulixee/client  @ulixee/client-playground

### ISSUE THREAD

**Issue by Aubermean** [ulixee/platform#192]
Hi,

The first hasn't been updated for ages, the second doesn't exist (is only referenced in docs). Is the only option to build from source? Attempting now, but a bit of a pain since it's also complaining about needing nodejs 19. Read the docs over and over, plus the examples, plus the Desktop app tutorial but cannot get it working without the client!

**Comment by blakebyrnes** [comment]
Hmm. Great question. I thought we had published the newer client over that very old version... but I don't see it now. I know we didn't do the client playground yet though. Let me see what happened

**Comment by Aubermean** [comment]
Don't mean to push on this during the holidays, but still have all my browser and terminal tabs open while trying to get ulixee up and running. Could you publish @ulixee/client to npm for me so I can get things moving to see if ulixee is right for me? I love the idea in principle but I want to verify whether it's all as good as it sounds. Thank you!

**Comment by blakebyrnes** [comment]
I think it should be up now at version 25. Let me know if you have any issues.

**Comment by Aubermean** [comment]
Still having issues getting their the wiki tutorials or Desktop tutorial going. I have tried for hours, but the examples and steps followed closely never results in what is expected - for example running the datstore with either example hangs, doesn't provide a uri, and has no visible way to debug the issue. There is also a mix of yarn and npx which is confusing. There is no clear recommended/supported versions for nodejs and python (I found nodejs 20 problematic, and nodejs 19 only worked when I dropped from python 3.12 to 3.8). Could you put your idiot hat on for us, run through the tutorial on a clean system and try to get the docs/tutorial working? I think it would help a lot of people get started, and you've put so much effort in the core codebase, the websites/docs, visuals, the desktop app, its a shame there is a hurdle for new users getting going...

**Comment by blakebyrnes** [comment]
Sorry you're having so many issues. Could you help give me a few of the examples you've tried that are failing? What is the python part for? I've gotten sidetracked with building out the payments system, and it looks like the dependencies on better-sqlite are causing you some of these issues, but I'd like to understand what the specific things you're hitting are. So.. on the flip side of your comment, can you put your own idiot hat on and walk me through the exact steps you're taking that are failing? In good news, I'm so close to getting back to this codebase, so I'll be able to sort out the dependency issues.


RE: yarn vs npx, some people prefer one vs the other. Are you saying we're toggling between sometimes writing the command in yarn, and sometimes in npx? I know there's a couple places we show both options, but agree we should either always be showing both, or pick one vs the other.

**Comment by Aubermean** [comment]
Yeah, I mean that you are muddling yarn npx, rather than chosing one or showing both side by side.

I found out a lot of issues I was having was down to the nodejs and python version pair, so providing a recommendation on that would help.

When I get back around to things, as I find issues I will drop back here and shout at the wind :)

Thank you for your fast reply, and thank you for the OSS, I really believe it has an obscene amount of potential but I can understand that things (and rabbit holes) always get in the way!

**Comment by Aubermean** [comment]
I know this isn't the best place - but can I ask, is it possible to use your (excellent) browser extension outside of the Uxilee desktop?

**Comment by blakebyrnes** [comment]
What are you meaning by extension? The replay tool? Can you tell me more about what you're hoping to do "outside ulixee desktop"?
