### ISSUE TITLE
Documentation doesn't align with functionality of platform-utils

### ISSUE THREAD

**Issue by morgano86** [ulixee/platform#215]
The documentation:
https://ulixee.org/docs/datastore/advanced/credits#admin

States:
> To create a new Identity, you can run: npx @ulixee/platform-utils identity

This results in:
> npx @ulixee/platform-utils identity
> npm error could not determine executable to run
> npm error A complete log of this run can be found in: /root/.npm/_logs/2024-11-18T13_11_27_417Z-debug-0.log

If I indicate to use a package I get:
> npx --package=@ulixee/platform-utils identity
> sh: 1: identity: not found

@ulixee/platform-utils doesn't have a bin in package.json for running cmd.

The only way to create an identity is to import Identity from platform-utils in my app and use "create".

Am I doing something wrong?

**Comment by blakebyrnes** [comment]
Ah, thanks. Docs got missed when this moved. Sorry about that. Will update. Should be under `npx @ulixee/datastore admin-identity`

**Comment by morgano86** [comment]
Just an FYI that CMD is also hardcoded in CloudNode:

https://github.com/ulixee/platform/blob/56a00b029d261f2d41d22b3edbd4bc6c28f1333c/cloud/main/lib/CloudNode.ts#L385

> ############################################################################################
> ############################################################################################
> ###########################  TEMPORARY NETWORK IDENTITY  ###################################
> ############################################################################################
> ############################################################################################
> 
>             A temporary networkIdentity has been installed on your server. 
> 
>        To create a long-term network identity, you should save and use this Identity 
>                           from your local system:
> 
>  npx @ulixee/platform-utils save-identity --privateKey=${key.toString('base64')} --filename="${path}"
> 
> --------------------------------------------------------------------------------------------
>        
>            To dismiss this message, add the following environment variable:
>            
>  ULX_NETWORK_IDENTITY_PATH="${path}",
> 
> ############################################################################################
> ############################################################################################
> ############################################################################################
